"""add cadidate model

Revision ID: 4d760a909ff5
Revises: 50e9417c3c19
Create Date: 2025-11-02 15:47:01.420543

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d760a909ff5"
down_revision: Union[str, Sequence[str], None] = "50e9417c3c19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("years_of_experience", sa.Float(), nullable=False),
        sa.Column("skills", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "experiences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("certifications", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_base_document_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_base_document_id"],
            ["knowledgebasedocument.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("knowledge_base_document_id"),
    )
    op.create_index(op.f("ix_candidate_email"), "candidate", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candidate_email"), table_name="candidate")
    op.drop_table("candidate")
    # ### end Alembic commands ###
