name: tars

services:
  db:
    container_name: tars-postgres
    image: postgres:18
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

  adminer:
    container_name: tars-adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  pgadmin:
    container_name: tars-pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 5050:80
    env_file: .env

volumes:
  pgdata: