target-version = "py312"

exclude = [".venv", "**/test/*.py"]

[format]
quote-style = "double"
docstring-code-format = true

[lint]
select = ["FAST001", "FAST002", "FAST003", "T201", "T203", "F401", "T201"]
preview = true

[lint.per-file-ignores]
"*.ipynb" = ["T201"]
